version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter-lab
    volumes:
      - ./code:/home/jupyter/code
    ports:
      - "8888:8888"
    working_dir: /home/jupyter/code
    command: >
      bash -c "pip install --upgrade pip 
      && pip install -r requirements-nlp-study.txt 
      && jupyter lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
