version: '3.8'
services:
  masterNode01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: master-node01
    environment:
      - node.name=master-node01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=master-node01,master-node02,master-node03
      - network.bind_host=0.0.0.0
      - network.publish_host=master-node01
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=master
      - http.port=9200
      - transport.port=9300
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - proxyserverslastic

  masterNode02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: master-node02
    environment:
      - node.name=master-node02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=master-node01,master-node02,master-node03
      - network.bind_host=0.0.0.0
      - network.publish_host=master-node02
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=master
      - http.port=9201
      - transport.port=9301
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9201
      - 9301:9301
    networks:
      - proxyserverslastic

  masterNode03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: master-node03
    environment:
      - node.name=master-node03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=master-node01,master-node02,master-node03
      - network.bind_host=0.0.0.0
      - network.publish_host=master-node03
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=master
      - http.port=9202
      - transport.port=9302
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
      - 9302:9302
    networks:
      - proxyserverslastic

  dataNode01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: data-node01
    environment:
      - node.name=data-node01
      - cluster.name=es-docker-cluster
      - network.bind_host=0.0.0.0
      - network.publish_host=data-node01
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=data
      - http.port=9203
      - transport.port=9303
      - transport.compress=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata01:/usr/share/elasticsearch/data
    ports:
      - 9203:9203
      - 9303:9303
    networks:
      - proxyserverslastic

  dataNode02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: data-node02
    environment:
      - node.name=data-node02
      - cluster.name=es-docker-cluster
      - network.bind_host=0.0.0.0
      - network.publish_host=data-node02
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=data
      - http.port=9204
      - transport.port=9304
      - transport.compress=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata02:/usr/share/elasticsearch/data
    ports:
      - 9204:9204
      - 9304:9304
    networks:
      - proxyserverslastic

  dataNode03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: data-node03
    environment:
      - node.name=data-node03
      - cluster.name=es-docker-cluster
      - network.bind_host=0.0.0.0
      - network.publish_host=data-node03
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=data
      - http.port=9205
      - transport.port=9305
      - transport.compress=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata03:/usr/share/elasticsearch/data
    ports:
      - 9205:9205
      - 9305:9305
    networks:
      - proxyserverslastic

  coordinateNode01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: coordinate-node01
    environment:
      - node.name=coordinate-node01
      - cluster.name=es-docker-cluster
      - network.bind_host=0.0.0.0
      - network.publish_host=coordinate-node01
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=[]
      - http.port=9210
      - transport.port=9310
      - transport.compress=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9210:9210
      - 9310:9310
    networks:
      - proxyserverslastic

  coordinateNode02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: coordinate-node02
    environment:
      - node.name=coordinate-node02
      - cluster.name=es-docker-cluster
      - network.bind_host=0.0.0.0
      - network.publish_host=coordinate-node02
      - discovery.seed_hosts=master-node01:9300,master-node02:9301,master-node03:9302
      - node.roles=[]
      - http.port=9211
      - transport.port=9311
      - transport.compress=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9211:9211
      - 9311:9311
    networks:
      - proxyserverslastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://nginxProxy-server:9000"]'
    networks:
      - proxyserverslastic

  nginxProxyServer:
    image: nginx:latest
    container_name: nginxProxy-server
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 9000:9000
    networks:
      - proxyserverslastic

volumes:
  elasticdata01:
    driver: local
  elasticdata02:
    driver: local
  elasticdata03:
    driver: local

networks:
  proxyserverslastic:
    driver: bridge